# Generated by Django 5.0.6 on 2024-05-14 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('Book_name', models.CharField(max_length=200)),
                ('Book_author', models.CharField(max_length=200)),
                ('no_page', models.IntegerField()),
                ('BookCover', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
                ('Book_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('Category_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='test',
        ),
        migrations.AddField(
            model_name='book',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Books', to='Site.categorys'),
        ),
    ]
