# Generated by Django 5.0.6 on 2024-05-14 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_book_categorys_delete_test_book_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Categorys',
        ),
    ]
