# Generated by Django 5.0.6 on 2024-05-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorys',
            name='Category_id',
            field=models.IntegerField(default=1),
        ),
    ]
