# Generated by Django 5.0.6 on 2024-05-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0006_remove_categorys_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorys',
            name='Category_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='categorys',
            name='Category_name',
            field=models.CharField(max_length=200),
        ),
    ]
