# Generated by Django 5.0.6 on 2024-05-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0007_categorys_category_id_alter_categorys_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorys',
            name='Category_id',
        ),
        migrations.AlterField(
            model_name='categorys',
            name='Category_name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
